<?php
// generate_excel.php
require_once __DIR__ . '/../../utilities/config.php';
require_once __DIR__ . '/../../utilities/utils.php';

session_start();

// Check if PhpSpreadsheet is installed
if (!class_exists('PhpOffice\PhpSpreadsheet\Spreadsheet')) {
    die('ERROR: PhpSpreadsheet not installed. Run: composer require phpoffice/phpspreadsheet');
}

// Now import the classes
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

$requestId = uniqid('excel_export_', true);
$ipAddress = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
$userId = $_SESSION['unique_id'] ?? 'guest';

// Check authentication
if (!isset($_SESSION['unique_id']) || !isset($_SESSION['role'])) {
    logActivity("[EXCEL_EXPORT_UNAUTH] [ID:{$requestId}] [IP:{$ipAddress}] Unauthenticated export attempt");
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit();
}

$userRole = $_SESSION['role'];
$allowedRoles = ['Super Admin', 'Admin'];

if (!in_array($userRole, $allowedRoles)) {
    logActivity("[EXCEL_EXPORT_UNAUTHORIZED] [ID:{$requestId}] [IP:{$ipAddress}] [User:{$userId}] [Role:{$userRole}] Unauthorized export attempt");
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Access denied']);
    exit();
}

// Get POST data
$input = file_get_contents('php://input');
if (empty($input)) {
    logActivity("[EXCEL_EXPORT_NO_DATA] [ID:{$requestId}] [User:{$userId}] No data received");
    // Return error as JSON
    header('Content-Type: application/json');
    echo json_encode(['success' => false, 'message' => 'No data provided']);
    exit();
}

$data = json_decode($input, true);

if (!$data || !isset($data['data'])) {
    logActivity("[EXCEL_EXPORT_INVALID_DATA] [ID:{$requestId}] [User:{$userId}] Invalid data structure");
    // Return error as JSON
    header('Content-Type: application/json');
    echo json_encode(['success' => false, 'message' => 'Invalid data structure']);
    exit();
}

logActivity("[EXCEL_EXPORT_START] [ID:{$requestId}] [User:{$userId}] Starting Excel export with " . ($data['data']['row_count'] ?? 0) . " rows");

try {
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();
    
    // Set title
    $sheet->setTitle('Query Results');
    
    // Add metadata row (optional)
    $sheet->setCellValue('A1', 'Generated: ' . date('Y-m-d H:i:s'));
    $sheet->setCellValue('A2', 'Generated By: ' . ($_SESSION['firstname'] ?? '') . ' ' . ($_SESSION['lastname'] ?? ''));
    $sheet->setCellValue('A3', 'Query: ' . (substr($data['query'] ?? '', 0, 100)));
    
    // Add headers starting from row 5
    $startRow = 5;
    $col = 1;
    foreach ($data['data']['columns'] as $header) {
        $sheet->setCellValueByColumnAndRow($col, $startRow, $header);
        
        // Style headers
        $cell = $sheet->getCellByColumnAndRow($col, $startRow);
        $coord = $cell->getCoordinate();
        
        // Style header cells
        $sheet->getStyle($coord)->getFont()->setBold(true);
        $sheet->getStyle($coord)->getFill()->setFillType(Fill::FILL_SOLID);
        $sheet->getStyle($coord)->getFill()->getStartColor()->setARGB('FFE0E0E0');
        $sheet->getStyle($coord)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        
        $col++;
    }
    
    logActivity("[EXCEL_EXPORT_HEADERS] [ID:{$requestId}] [User:{$userId}] Added " . count($data['data']['columns']) . " columns");
    
    // Add data
    $row = $startRow + 1;
    $dataCount = 0;
    foreach ($data['data']['data'] as $record) {
        $col = 1;
        foreach ($data['data']['columns'] as $column) {
            $value = $record[$column] ?? '';
            
            // Handle different data types
            if (is_numeric($value) && !is_string($value)) {
                $sheet->setCellValueByColumnAndRow($col, $row, (float)$value);
            } else {
                $sheet->setCellValueByColumnAndRow($col, $row, (string)$value);
            }
            
            $col++;
        }
        $row++;
        $dataCount++;
        
        // Log progress for large datasets
        if ($dataCount % 1000 === 0) {
            logActivity("[EXCEL_EXPORT_PROGRESS] [ID:{$requestId}] [User:{$userId}] Processed {$dataCount} rows...");
        }
    }
    
    logActivity("[EXCEL_EXPORT_DATA_ADDED] [ID:{$requestId}] [User:{$userId}] Added {$dataCount} rows of data");
    
    // Auto-size columns
    $lastColumn = $sheet->getHighestColumn();
    for ($col = 'A'; $col <= $lastColumn; $col++) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
    }
    
    // Add borders to data range
    $lastRow = $startRow + $dataCount;
    $dataRange = 'A' . $startRow . ':' . $lastColumn . $lastRow;
    $sheet->getStyle($dataRange)->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
    
    // Center-align all cells
    $sheet->getStyle('A1:' . $lastColumn . $lastRow)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
    
    logActivity("[EXCEL_EXPORT_AUTOSIZE] [ID:{$requestId}] [User:{$userId}] Auto-sized columns and added borders");
    
    // Set headers for Excel download
    $filename = 'query-results_' . date('Y-m-d_H-i-s') . '.xlsx';
    
    // Clear any previous output
    if (ob_get_length()) ob_end_clean();
    
    // Set Excel headers
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment;filename="' . $filename . '"');
    header('Cache-Control: max-age=0');
    header('Pragma: public');
    header('Expires: 0');
    
    // Create writer
    $writer = new Xlsx($spreadsheet);
    
    // Save to temporary file to get size
    $tempFile = tempnam(sys_get_temp_dir(), 'excel_');
    $writer->save($tempFile);
    $fileSize = filesize($tempFile);
    
    // Update content length
    header('Content-Length: ' . $fileSize);
    
    // Output the file
    readfile($tempFile);
    
    // Clean up
    unlink($tempFile);
    
    logActivity("[EXCEL_EXPORT_SUCCESS] [ID:{$requestId}] [User:{$userId}] Excel export completed successfully, file size: {$fileSize} bytes");
    exit;
    
} catch (Exception $e) {
    logActivity("[EXCEL_EXPORT_ERROR] [ID:{$requestId}] [User:{$userId}] Error: " . $e->getMessage());
    
    // Return error as JSON
    header('Content-Type: application/json');
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
}