CREATE TABLE properties (
id INT(11) NOT NULL AUTO_INCREMENT,
agent_id INT(11) NOT NULL,
property_code VARCHAR(100) NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
address VARCHAR(512) DEFAULT NULL,
city VARCHAR(100) DEFAULT NULL,
state VARCHAR(100) DEFAULT NULL,
country VARCHAR(100) DEFAULT 'Nigeria',
contact_name VARCHAR(255) DEFAULT NULL,
contact_phone VARCHAR(50) DEFAULT NULL,
notes TEXT DEFAULT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);