<?php
// generate_pdf.php
header('Content-Type: application/json');
require_once __DIR__ . '/../../utilities/config.php';
require_once __DIR__ . '/../../utilities/utils.php';

session_start();

$requestId = uniqid('pdf_export_', true);
$ipAddress = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
$userId = $_SESSION['unique_id'] ?? 'guest';

// Check authentication
if (!isset($_SESSION['unique_id']) || !isset($_SESSION['role'])) {
    logActivity("[PDF_EXPORT_UNAUTH] [ID:{$requestId}] [IP:{$ipAddress}] Unauthenticated PDF export attempt");
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit();
}

$userRole = $_SESSION['role'];
$allowedRoles = ['Super Admin', 'Admin'];

if (!in_array($userRole, $allowedRoles)) {
    logActivity("[PDF_EXPORT_UNAUTHORIZED] [ID:{$requestId}] [IP:{$ipAddress}] [User:{$userId}] [Role:{$userRole}] Unauthorized PDF export attempt");
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Access denied']);
    exit();
}

// Check if TCPDF is available
$tcpdfPath = __DIR__ . '/../../vendor/tecnickcom/tcpdf/tcpdf.php';
if (!file_exists($tcpdfPath)) {
    logActivity("[PDF_EXPORT_MISSING_DEPS] [ID:{$requestId}] [User:{$userId}] TCPDF not found at: {$tcpdfPath}");
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'PDF export requires TCPDF library']);
    exit();
}

require_once $tcpdfPath;

// Get POST data
$input = file_get_contents('php://input');
if (empty($input)) {
    logActivity("[PDF_EXPORT_NO_DATA] [ID:{$requestId}] [User:{$userId}] No data received");
    echo json_encode(['success' => false, 'message' => 'No data provided']);
    exit();
}

$data = json_decode($input, true);

if (!$data || !isset($data['data'])) {
    logActivity("[PDF_EXPORT_INVALID_DATA] [ID:{$requestId}] [User:{$userId}] Invalid data structure");
    echo json_encode(['success' => false, 'message' => 'Invalid data structure']);
    exit();
}

$rowCount = $data['data']['row_count'] ?? 0;
$colCount = count($data['data']['columns'] ?? []);

logActivity("[PDF_EXPORT_START] [ID:{$requestId}] [User:{$userId}] Starting PDF export with {$rowCount} rows and {$colCount} columns");

try {
    // Create new PDF document
    $pdf = new TCPDF('L', PDF_UNIT, 'A4', true, 'UTF-8', false);
    
    // Set document information
    $pdf->SetCreator('Property Management System');
    $pdf->SetAuthor('System Admin');
    $pdf->SetTitle('Query Report');
    $pdf->SetSubject('SQL Query Results');
    
    // Remove default header/footer
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    
    // Add a page
    $pdf->AddPage();
    
    // Set font
    $pdf->SetFont('helvetica', '', 10);
    
    // Title
    $title = isset($data['title']) ? $data['title'] : 'SQL Query Report';
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 10, $title, 0, 1, 'C');
    $pdf->SetFont('helvetica', '', 10);
    
    // Query preview
    if (isset($data['query'])) {
        $queryPreview = strlen($data['query']) > 150 ? substr($data['query'], 0, 150) . '...' : $data['query'];
        $pdf->Cell(0, 6, 'Query: ' . $queryPreview, 0, 1);
    }
    
    // Timestamp
    $timestamp = isset($data['timestamp']) ? $data['timestamp'] : date('Y-m-d H:i:s');
    $pdf->Cell(0, 6, 'Generated: ' . $timestamp, 0, 1);
    
    // User info
    $pdf->Cell(0, 6, 'Generated by: ' . ($_SESSION['firstname'] ?? 'Unknown') . ' ' . ($_SESSION['lastname'] ?? ''), 0, 1);
    
    $pdf->Ln(10);
    
    // Check if data is too large for PDF
    if ($rowCount > 1000) {
        $pdf->Cell(0, 6, 'Note: Showing first 1000 rows of ' . $rowCount . ' total rows', 0, 1);
        $pdf->Ln(5);
    }
    
    // Create table header
    $html = '<table border="1" cellpadding="4" style="border-collapse: collapse; font-size: 9pt;">';
    
    // Header row
    $html .= '<tr style="background-color: #f2f2f2; font-weight: bold;">';
    foreach ($data['data']['columns'] as $header) {
        $colWidth = min(100 / $colCount, 30); // Max 30% per column
        $html .= '<th width="' . $colWidth . '%">' . htmlspecialchars($header) . '</th>';
    }
    $html .= '</tr>';
    
    logActivity("[PDF_EXPORT_CREATING_TABLE] [ID:{$requestId}] [User:{$userId}] Creating table with {$colCount} columns");
    
    // Data rows
    $rowsProcessed = 0;
    $maxRows = min($rowCount, 1000); // Limit to 1000 rows for PDF
    
    foreach ($data['data']['data'] as $index => $row) {
        if ($index >= $maxRows) break;
        
        $html .= '<tr>';
        foreach ($data['data']['columns'] as $column) {
            $value = isset($row[$column]) ? htmlspecialchars(substr($row[$column], 0, 100)) : '';
            $html .= '<td>' . $value . '</td>';
        }
        $html .= '</tr>';
        $rowsProcessed++;
        
        // Log progress
        if ($rowsProcessed % 200 === 0) {
            logActivity("[PDF_EXPORT_PROGRESS] [ID:{$requestId}] [User:{$userId}] Processed {$rowsProcessed}/{$maxRows} rows...");
        }
    }
    
    $html .= '</table>';
    
    logActivity("[PDF_EXPORT_TABLE_CREATED] [ID:{$requestId}] [User:{$userId}] Table created with {$rowsProcessed} rows");
    
    // Footer with row count
    $pdf->Ln(5);
    $pdf->Cell(0, 6, 'Rows displayed: ' . $rowsProcessed . ' of ' . $rowCount . ' total', 0, 1);
    
    if ($rowCount > $maxRows) {
        $pdf->Cell(0, 6, 'Note: Only first ' . $maxRows . ' rows shown in PDF. Export to Excel for full dataset.', 0, 1);
    }
    
    // Write HTML content
    logActivity("[PDF_EXPORT_WRITING_HTML] [ID:{$requestId}] [User:{$userId}] Writing HTML table to PDF");
    $pdf->writeHTML($html, true, false, true, false, '');
    
    // Output PDF
    $filename = 'query-report_' . date('Y-m-d_H-i-s') . '.pdf';
    
    logActivity("[PDF_EXPORT_SUCCESS] [ID:{$requestId}] [User:{$userId}] PDF created successfully, outputting file: {$filename}");
    
    $pdf->Output($filename, 'D');
    exit;
    
} catch (Exception $e) {
    logActivity("[PDF_EXPORT_ERROR] [ID:{$requestId}] [User:{$userId}] Error: " . $e->getMessage());
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
}